# Generated by Django 2.0.6 on 2018-06-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0003_auto_20180123_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),

        migrations.RenameField(
            model_name='survey',
            old_name='mapping_id',
            new_name='project_id',
        ),
    ]
