# Generated by Django 2.0.6 on 2018-06-04 11:05

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0004_delete_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokens',
            name='kernel_token',
            field=models.CharField(blank=True, help_text='This token corresponds to an Aether Kernel authorization token linked to this user.', max_length=40, null=True, verbose_name='Aether Kernel token'),
        ),
        migrations.AlterField(
            model_name='usertokens',
            name='odk_token',
            field=models.CharField(blank=True, help_text='This token corresponds to an Aether ODK authorization token linked to this user.', max_length=40, null=True, verbose_name='Aether ODK token'),
        ),
        migrations.AlterField(
            model_name='usertokens',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='app_tokens', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterModelOptions(
            name='usertokens',
            options={'verbose_name': 'user authorization tokens', 'verbose_name_plural': 'users authorization tokens'},
        ),


        migrations.AlterField(
            model_name='survey',
            name='project_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='This ID corresponds to an Aether Kernel project ID.', primary_key=True, serialize=False, verbose_name='project ID'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.TextField(blank=True, default='', null=True, verbose_name='name'),
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'survey', 'verbose_name_plural': 'surveys'},
        ),


        migrations.AlterField(
            model_name='mask',
            name='columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(verbose_name='column internal name'), help_text='Comma separated list of column internal names', size=None, verbose_name='masked columns'),
        ),
        migrations.AlterField(
            model_name='mask',
            name='name',
            field=models.TextField(verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='mask',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masks', to='gather.Survey', verbose_name='survey'),
        ),
        migrations.AlterModelOptions(
            name='mask',
            options={'verbose_name': 'mask', 'verbose_name_plural': 'masks'},
        ),
    ]
