# Generated by Django 2.1.1 on 2018-10-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0005_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertokens',
            name='couchdb_sync_token',
            field=models.CharField(blank=True, help_text='This token corresponds to an Aether CouchDB-Sync authorization token linked to this user.', max_length=40, null=True, verbose_name='Aether CouchDB-Sync token'),
        ),
    ]
