# Generated by Django 2.2.1 on 2019-05-02 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0100_initial_squashed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTokens',
        ),
    ]
