# Generated by Django 2.2.7 on 2019-11-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0101_delete_usertokens'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mask',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='mask',
            constraint=models.UniqueConstraint(fields=('survey', 'name'), name='unique_mask_name_by_survey'),
        ),
    ]
