# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 13:16
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('columns', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
            options={
                'default_related_name': 'masks',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'default_related_name': 'surveys',
            },
        ),
        migrations.AddField(
            model_name='mask',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masks', to='ui.Survey'),
        ),
        migrations.AlterUniqueTogether(
            name='mask',
            unique_together=set([('survey', 'name')]),
        ),
    ]
